name: Build-Latex-PDF

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

        # Lint LaTeX files (spanish)
      - name: Lint LaTeX files
        uses: ChiefGokhlayeh/textidote-action@v5
        id: lint
        with:
          root_file: main.tex
          working_directory: ./src
      - name: Throw error if linter warnings exist
        if: ${{ steps.lint.outputs.num_warnings != 0 }}
        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
